config/routes.rb
Rails.application.routes.draw do


root "huts#index"

resources :huts, only: [:index, :show]
resources :hut, only: [:index, :new, :create, :show]

end

app/models/hut.rb
class Hut < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/huts_controller.rb
class HutsController < ApplicationController
  def index
		@huts = Hut.all
  end

  def new
  		@hut = Hut.new
  end


  def show
  	    @hut = Hut.find(params[:id])
  end


  def edit
  end


  def create
		@hut = Hut.new(hut_params)
		
		if @hut.save
			flash[:success] = "Thanks for adding a new hut"
			redirect_to root_path
		else
			flash[:error] = "Oops, something is missing"
			render :new
		end

  end


private
def hut_params
	params.require(:hut).permit(:serial, :longitude, :latitude, :comments)
end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/huts_helper.rb
module HutsHelper
end

app/views/huts/_form.html.erb
<% @hut.errors.full_messages %>

<%= simple_form_for @hut do |form| %>
	


	<%= form.input :serial  %>
	<%= form.input :latitude  %>
	<%= form.input :longitude  %>
	<%= form.input :comments  %>


	<%= form.button :submit %>

<% end %>

app/views/huts/edit.html.erb
<h1>Huts#edit</h1>
<p>Find me in app/views/huts/edit.html.erb</p>

app/views/huts/index.html.erb
<ul>
<% @huts.each do |hut| %>

	<section class="hut">


		<%= link_to root_path(search: { q: hut.serial }) do %>

			<li data-lat="<%= hut.latitude %>" data-lng="<%= hut.longitude %>" >
			<p>Serial Number: <%= hut.serial %> </p>
			<p>Setup by: <%= hut.user_ID %> </p></li>

	<% end %>

	</section>

<% end %>

</ul>



<section class="map"></section>

<%= link_to "Add a Hut", new_hut_path, class: 'button' %>

app/views/huts/new.html.erb
<%= render "form" %>

app/views/huts/show.html.erb
<section class="hut">
  <h2><%= @hut.serial %></h2>

  <div class="location"><p><%= @hut.longitude %>, <%= @hut.latitude %></p></div>


  <section class="map show" data-lat="<%= @hut.latitude %>" data-lng="<%= @hut.longitude %>"></section>
  <%= simple_format @hut.comments %>


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Huttracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= params[:action] %>">

<header>
	<nav>
		<h1><%= link_to "Huttracker", root_path %></h1>

		<h2>Remote information on outdoor huts</h2> </br>
		</br>

	</nav>



</header>

<% flash.each do |key, value| %>
	<div class="<%= key %>">
		<p><%= value %></p>
	</div>
<% end %>


<%= yield %>

<h>

</body>
</html>